export const allNeighborhoods = [
  'Ramat Eshkol',
  'Gush 80',
  'Jerusalem Estates',
  'Romema',
  'Minchas Yitzchok',
  'Rechavia',
  'Shaarei Chesed',
  'Baka',
  'German Colony',
  'Katamon',
  'Mamilla',
  'Nachlaot',
  'Talbiya',
  'Ein Kerem',
  'Old City',
  'City Center',
  'Givat Shaul',
  'Har Nof',
  'Bayit Vegan',
  'Kiryat Moshe',
  'Neve Yaakov',
  'Pisgat Zeev',
  'French Hill',
  'Sanhedria',
  'Mea Shearim',
  'Geula',
  'Armon Hanatziv',
  'Abu Tor',
  'Arnona',
  'Malha',
  'Gilo',
  'Pat',
  'Neve Granot',
  'Neve Shaanan',
  'Beit Hakerem',
  'Sorotzkin',
  'Mattersdorf',
  'Panim Meirot',
  'Kiryat Belz',
  'Kiryat Sanz',
  'Zichron Moshe',
  'Bucharim',
  'Batei Ungarin',
  'Batei Warsaw',
  'Ezras Torah',
  'Unsdorf',
  'Kiryat Itri',
  'Ramat Shlomo',
  'Beitar Illit',
  'Ramot',
  'Ramot Aleph',
  'Ramot Bet',
  'Ramot Gimmel',
  'Ramot Dalet',
  'Kiryat Mattersdorf',
  'Sanhedria Murchevet',
  'Schneller',
  'Makor Baruch',
  'Kerem Avraham',
  'Kiryat Zanz',
  'Mekor Chaim',
  'Ir Ganim',
  'Kiryat Menachem',
  'Kiryat Yovel',
  'Givat Mordechai',
  'Rasko',
  'Shikun Chabad',
  'Bar Ilan',
  'Shmuel Hanavi',
  'Yemin Moshe',
  'Talpiot',
  'Maalot Dafna',
  'Malchei Yisrael',
  'Strauss',
  'Yaffo',
  'King George',
  'Ben Yehuda',
  'Emek Refaim',
  'Azza',
]

export const defaultPopularNeighborhoods = [
  'Ramat Eshkol',
  'Rechavia',
  'German Colony',
  'Romema',
]

export const defaultExploreNeighborhoods = [
  'Ramat Eshkol',
  'Gush 80',
  'Romema',
  'Jerusalem Estates',
  'Minchas Yitzchok',
  'Rechavia',
]
