/**
 * Shared Open Graph / Twitter image helpers.
 *
 * Next.js merges metadata shallowly: a page that sets its own `openGraph`
 * REPLACES the parent layout's `openGraph` wholesale — including its images.
 * So every page that customises `openGraph` must also re-supply an image, or it
 * renders with no share card at all. Spread these into each page's metadata:
 *
 *   openGraph: { ...ogImages('Pesach stays in Jerusalem'), title, description },
 *   twitter: { card: 'summary_large_image', images: ogTwitterImages('Pesach stays') },
 *
 * The image itself is generated by /api/og as a PNG (see app/api/og/route.tsx),
 * which every scraper renders reliably. `metadataBase` in the root layout turns
 * the relative /api/og path into the absolute URL that scrapers require.
 */

function ogUrl(title?: string) {
  if (!title) return '/api/og'
  return `/api/og?title=${encodeURIComponent(title)}`
}

export function ogImages(title?: string) {
  return {
    images: [
      {
        url: ogUrl(title),
        width: 1200,
        height: 630,
        alt: title ? `${title} — JLM Collective` : 'JLM Collective',
      },
    ],
  }
}

export function ogTwitterImages(title?: string) {
  return [ogUrl(title)]
}
